version: '2.1'

services:



  api-gateway:

   build: zuul-apigateway/

   depends_on:

    eureka-server:

     condition: service_healthy

   restart: always

   network_mode: "host"

   image: demo-zuul-service

   hostname: localhost

   ports:

    - 8092:8092

   healthcheck:

    test: "exit 0"





  eureka-server:

   build: eureka-server/

   restart: always

   network_mode: "host"

   image: demo-eureka-service

   hostname: localhost

   ports:

    - 9090:9090

   healthcheck:

    test: "exit 0"





  userprofile:

   build: user-profile/

   restart: always

   network_mode: host

   container_name: userprofile

   depends_on:

    mongo:
     condition: service_healthy
    eureka-server:
     condition: service_healthy
    api-gateway:
     condition: service_healthy
    config-service:
     condition: service_healthy

   ports:

    - 8040:8040

   healthcheck:

    test: "exit 0"





  config-service:

   build: config-service/

   image: config-server

   container_name: config-server

   restart: always
   depends_on:
    eureka-server:

     condition: service_healthy
   

   network_mode: "host"

   hostname: localhost

   ports:

    - 8891:8891

   healthcheck:

    test: "exit 0"






  screening:

   build: movie-schedule/

   restart: always

   network_mode: host

   container_name: screening

   depends_on:

    mongo:
     condition: service_healthy
    eureka-server:
     condition: service_healthy
    api-gateway:
     condition: service_healthy
    config-service:
     condition: service_healthy

   ports:

    - 8030:8030

   healthcheck:

    test: "exit 0"




  
  mongo:

   image: mongo

   network_mode: host

   container_name: spring-mongo

   ports:

    - 27017:27017

   volumes:

    - /usr/src/home:/data/db
   healthcheck:

    test: "exit 0"


  juggler-front-end:

   image: viship/juggler:1.0.0

   container_name: juggler-front-end

   ports:
    - 4200:4200


