#spring:
# application:
# name: movie-schedule
# data:
#  mongodb:
#    database: movie-schedule
#   host: localhost
#    port: "27017"
#    uri: mongodb://localhost/movie-schedule
#    username: ""
#eureka:
# client:
#  register-with-eureka: "true"
#  fetch-registry: "true"
#  serviceUrl:
#    defaultZone: http://localhost:9084/eureka/
server:
 port: "9072"
